name: Deploy demo

# Action will run on pushes to selected branches
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      password:
        description: "Password for the deployment"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy pipeline with branch specific parameters
      - name: Mask input value
        run: |
          PASSWORD=${{ github.event.inputs.password }}
          echo ::add-mask::$PASSWORD
          echo API_PASSWORD=$PASSWORD >> $GITHUB_ENV
      - name: Deploy data pipeline
        run: |
          echo "Deploying data pipeline"
          echo ${{env.API_PASSWORD}}
